"""empty message

Revision ID: c666a2d14d2a
Revises: a462b034d2c4
Create Date: 2020-06-20 21:42:47.363393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c666a2d14d2a'
down_revision = 'a462b034d2c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('City', sa.Column('state', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('City', 'state')
    # ### end Alembic commands ###
